version: '2'
services:
  mongodb:
    image: mongo:3.2
    hostname: mongodb
    ports:
      - "27017:27017"    
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/mongod.conf.orig:/etc/mongod.conf.orig
      - ./docker/mongo/logs/:/var/log/mongodb/
  embedded2Mongo:
    image: jackin/embedded2mongo:latest
    hostname: localhost
    ports:
      - "9999:9999"
    volumes:
      - ./docker/embedded2Mongo/resources/application.yml:/application.yml
    depends_on:
     - mongodb
    build:
     context: docker/embedded2Mongo
     dockerfile: docker/Dockerfile
